version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/FlacheQL
hooks:
  # BeforeInstall:
  #   - location: dpl_scripts/clear.sh
  #     timeout: 30
  #     runas: root
  ApplicationStart:
    - location: dpl_scripts/start_server.sh
      timeout: 180
      runas: root
#   ValidateService:
#     - location: SGA_Apex_REST_API_WAR/src/main/resources/scripts/validate-service.sh
#       timeout: 180
#       runas: root